### ISSUE TITLE
Stable version?

### ISSUE THREAD

**Issue by waldnercharles** [flathub/org.pegasus_frontend.Pegasus#14]
It looks like this flatpak points to the continuous tag of Pegasus. Is it possible to instead grab whatever the latest stable release is? Supporting themes based on a nightly build is problematic.

**Comment by j8r** [comment]
I think the theme API is quite stable as this point, doesn't it @mmatyas ?
Using the [latest stable release](https://github.com/mmatyas/pegasus-frontend/releases/latest) can be a good idea noneless, now that the flatpak and pegasus itself are even more stable than before.

I know how to do it with @flathubbot, it will have the advantage of beinf notified if a build fails, like for #13 .

**Comment by j8r** [comment]
I think the theme API is quite stable as this point, doesn't it @mmatyas ?
Using the [latest stable release](https://github.com/mmatyas/pegasus-frontend/releases/latest) can be a good idea noneless, now that the flatpak and pegasus itself are even more stable than before.

I know how to do it with @flathubbot, it will have the advantage of being notified if a build fails, like for #13 .

**Comment by waldnercharles** [comment]
Despite how stable Pegasus' api normally is, the nightly build is still less stable than the latest stable release. Even innocuous changes may meaningfully impact certain themes. For example, there are some breaking changes for my theme between alpha16 and the nightly build currently. 

In the nightly build `api.allGames` is a `GameListModel` rather than a `QQmlObjectListModel` like it was in alpha16, so it's missing some members that were originally exposed by `QQmlObjectListModel`

**Comment by mmatyas** [comment]
The problem is that, as far as I know, FlatHub supports only one single release channel for apps. To bring the latest fixes, including Flatpak support improvements, the continuous release was chosen [in this related discussion](https://github.com/mmatyas/pegasus-frontend/pull/867#issuecomment-891913962) for that.

**Comment by j8r** [comment]
Your options are either:
- build locally the flatpak for a given commit
- install a given release from flathub:
`flatpak remote-info --log flathub org.pegasus_frontend.Pegasus`
`flatpak update --commit=HASH org.pegasus_frontend.Pegasus` 

For the last option, you may want to disable any further update: `flatpak mask org.pegasus_frontend.Pegasus`

You may not find the exact commit of a [given release](https://github.com/mmatyas/pegasus-frontend/releases) - which is essentially a point-in-time snapshot from master - because the update from upstream is done once a day currently.
Even using @flathubbot can result to some commits skipped, because we will only merge the latest commit if multiple PRs are created in a short span.

**Comment by mmatyas** [comment]
I suppose this can be closed.

Also related: #15.
